---
abstract: 'Simple profiler'
author:
  - 'Yasuhiro Onishi <yasuhiro.onishi@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-KYTProf
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Data::Inheritable: 0
  Term::ANSIColor: 0
  Time::HiRes: 0
  UNIVERSAL::require: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/onishi/perl5-devel-kytprof.git
version: 0.02
